### PR TITLE
user email displays in navbar

### PR DESCRIPTION
**Pull request by joeybiotti**
## Status
Choose:
**READY**

## Description
When user logs in, their email address is displayed in navbar, as is "Add Product To Sell". User can click on hyperlink and is brought to "Products/Create". User can enter in information (name, description, type and price are all required) and then click the Create button. The product is then added to the database. 

_Before testing can be completed, you'll need to create a product type. To do this, go to localhost:xxxx/ProductTypes/Create and create a type. This is required to add an item._

## Todos (Checkmark what has been completed)
- [x] Tests
- [ ] Documentation

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```
git fetch --all
git branch -avv
git checkout jb-addProductToSell
git pull origin jb-addProductToSell
```

## Impacted Areas in Application
List general components of the application that this PR will affect:
Ticket 1-- Complete. 

Controllers/ProductController.cs
Views/Products/Create.cshtml
Views/Shared/_LoginPartial.cshtml

### CODE REVIEW

**Comment by sleuthy** [comment]
@joeybiotti 
In shared/_LoginPartial.cshtml -- needed to change "product" to "products" in navbar (to correspond to the ProductsController) to fix the redirect issue. :1st_place_medal:

**Comment by sleuthy** [comment]
First two "Given"s of #1 are complete.
Can manually add a Category (ProductType) in local database to test out Create functionality (location and photo are nullable fields).

**Comment by krissycaron** [comment]
👍 Works. Was able to register, Log in see my email and create a product.

**Comment by ollieOsh** [comment]
👍

**Pull request merged**
